const data = {
  products: [
    {
      // _id: '2',
      name: 'Charnay creme pour le change',
      slug: 'Charnay creme pour le change',
      category: 'bebe',
      image: '/images/prod2.jpg',
      price: 9.002,
      countInStock: 1000,
      referance: 'CHLV-007',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '3',
      name: 'Charnay eau parfumée 220ml ',
      slug: 'Charnay eau parfumée 220ml',
      category: 'bebe',
      image: '/images/prod3.jpg',
      price: 13.388,
      countInStock: 5000,
      referance: 'CHLV-001',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay cicatrisantspray35ml ',
      slug: 'Charnay cicatrisantspray35ml',
      category: 'all',
      image: '/images/prod4.jpg',
      price: 10.115,
      countInStock: 0,
      referance: 'CHCS-006',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay cicapaisyl 15gr',
      slug: 'Charnay cicapaisyl 15gr',
      category: 'all',
      image: '/images/prod5.jpg',
      price: 9.520,
      countInStock: 5,
      referance: 'CHLV-009',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay coli calm 30ml',
      slug: 'Charnay coli calm 30ml',
      category: 'bebe',
      image: '/images/prod6.jpg',
      price: 6.712,
      countInStock: 50,
      referance: 'CHCC-004',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay gel intime 5,5 100ml',
      slug: 'Charnay gel intime 5,5 100ml',
      category: 'Adulte',
      image: '/images/prod7.jpg',
      price: 9.002,
      countInStock: 10,
      referance: 'CHGF-002',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay liniment 200ml',
      slug: 'Charnay liniment 200ml',
      category: 'bebe',
      image: '/images/prod8.jpg',
      price: 12.852,
      countInStock: 2,
      referance: 'CHL-003',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay gel lavant doux 200ml',
      slug: 'Charnay gel lavant doux 200ml',
      category: 'bebe-enfants',
      image: '/images/prod9.jpg',
      price: 12.566,
      countInStock: 12,
      referance: 'CHLV-008',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
    {
      // _id: '4',
      name: 'Charnay Shampooing',
      slug: 'Charnay Shampooing',
      category: 'bebe-enfants',
      image: '/images/prod10.jpg',
      price: 12.852,
      countInStock: 9,
      referance: 'CHS-001',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
   
    {
      // _id: '4',
      name: 'Charnay congestyl 50gr',
      slug: 'Charnay congestyl 50gr',
      category: 'bebe',
      image: '/images/prod12.jpg',
      price: 5.772,
      countInStock: 1,
      referance: 'CHC-005',
      rating:5,
      numReviews: 23,
      description: 'high quality Tomato',
    },
  ],
};
export default data;
